version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dungeon_keeper.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./src:/app/src
      - ./dungeon_keeper.db:/app/dungeon_keeper.db
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dungeon_keeper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: