version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dungeon_keeper.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./dungeon_keeper.db:/app/dungeon_keeper.db
      - ./uploads:/app/uploads
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm start

volumes:
  db_data:
  uploads: